
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int doub = 24;
  public static final int pyc = 6;
  public static final int dsp = 7;
  public static final int cadena = 3;
  public static final int defglo = 21;
  public static final int decimal = 2;
  public static final int coma = 13;
  public static final int tituloy = 27;
  public static final int titulox = 26;
  public static final int caracter = 19;
  public static final int grafpie = 17;
  public static final int titulo = 25;
  public static final int gerest = 20;
  public static final int ejex = 28;
  public static final int guion = 8;
  public static final int punto = 9;
  public static final int igual = 10;
  public static final int EOF = 0;
  public static final int graflinea = 18;
  public static final int id = 14;
  public static final int str = 23;
  public static final int grafbar = 16;
  public static final int error = 1;
  public static final int orr = 11;
  public static final int entero = 15;
  public static final int corc = 30;
  public static final int mas = 12;
  public static final int llavec = 5;
  public static final int cora = 29;
  public static final int llavea = 4;
  public static final int compare = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "decimal",
  "cadena",
  "llavea",
  "llavec",
  "pyc",
  "dsp",
  "guion",
  "punto",
  "igual",
  "orr",
  "mas",
  "coma",
  "id",
  "entero",
  "grafbar",
  "grafpie",
  "graflinea",
  "caracter",
  "gerest",
  "defglo",
  "compare",
  "str",
  "doub",
  "titulo",
  "titulox",
  "tituloy",
  "ejex",
  "cora",
  "corc"
  };
}

