
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int porcen = 8;
  public static final int pyc = 6;
  public static final int dsp = 7;
  public static final int cadena = 3;
  public static final int oguion = 27;
  public static final int coma = 13;
  public static final int letraexp = 2;
  public static final int conj = 14;
  public static final int caracter = 26;
  public static final int guion = 9;
  public static final int punto = 10;
  public static final int EOF = 0;
  public static final int letra = 20;
  public static final int id = 18;
  public static final int error = 1;
  public static final int orr = 11;
  public static final int casod = 24;
  public static final int entero = 19;
  public static final int casoc = 23;
  public static final int caracteresp = 25;
  public static final int casob = 22;
  public static final int asterisco = 16;
  public static final int casoa = 21;
  public static final int mas = 12;
  public static final int interrogacion = 15;
  public static final int llavec = 5;
  public static final int llavea = 4;
  public static final int mayor = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "letraexp",
  "cadena",
  "llavea",
  "llavec",
  "pyc",
  "dsp",
  "porcen",
  "guion",
  "punto",
  "orr",
  "mas",
  "coma",
  "conj",
  "interrogacion",
  "asterisco",
  "mayor",
  "id",
  "entero",
  "letra",
  "casoa",
  "casob",
  "casoc",
  "casod",
  "caracteresp",
  "caracter",
  "oguion"
  };
}

